name: 000. Setup Terraform AWS

on:
  workflow_dispatch:
    inputs:
      # Força a confirmação manual da destruição na interface do Actions
      confirm_destroy:
        description: "Confirmação de Setup: Digite 'setup' para continuar."
        required: true
        default: ""
        type: string
  
env:
  TF_WORKING_DIR: ./iac/backend
  AWS_REGION: us-east-1
  DYNAMO_LOCK_TABLE: pucrs-crypto-terraform-lock
  S3_STATE: pucrs-crypto-github-action-tfstate-unique

jobs:
  prepare:
    name: 'Criar Recursos de Estado Remoto'
    runs-on: ubuntu-latest

    #Proteção para garantir que o usuário digitou 'setup'
    if: github.event.inputs.confirm_destroy == 'setup'

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configurar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Init (Estado Local)
        id: init
        run: terraform init

      - name: Terraform Apply (Criar S3 e DynamoDB)
        id: apply
        run: terraform apply -auto-approve