name: 001. Setup Infra AWS

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'Escolha a aÃ§Ã£o do Terraform (plan/apply)'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply

   
env:
  TF_WORKING_DIR: ./iac/flow
  AWS_REGION: us-east-1

jobs:
  terraform:
    name: 'Terraform ${{ github.event.inputs.terraform_action }}'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    outputs:
      apply_done: ${{ steps.apply_status.outputs.apply_done }}

    steps:
      - name: ðŸ“¦ Checkout Code
        uses: actions/checkout@v4

      - name: ðŸ” Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: âš™ï¸ Configurar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: ðŸ§± Terraform Init
        id: init
        run: terraform init -reconfigure

      - name: ðŸ§© Terraform Plan
        id: plan
        # if : always()
        run: terraform plan -out=tfplan

      - name: ðŸ§ª Validar CÃ³digo Terraform
        run: terraform validate
        if: github.event.inputs.terraform_action == 'apply'
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: ðŸš€ Terraform Apply
        id: apply
        if: github.event.inputs.terraform_action == 'apply'
        run: terraform apply -auto-approve tfplan

      - name: ðŸ“¤ Exportar CloudFront Distribution ID
        id: export_cf_id
        if: steps.apply.outcome == 'success'
        working-directory: ./iac/flow 
        run: |
          # Tenta obter o ID. 
          # 2>/dev/null: Ignora Warnings (como "No outputs found") para que o shell nÃ£o capture texto indesejado.
          ID=$(terraform output -raw cloudfront_distribution_id 2>/dev/null)
              
          # Verifica se a variÃ¡vel ID estÃ¡ vazia. Se estiver, falha o passo explicitamente.
          if [ -z "$ID" ]; then
            echo "âŒ ERRO: O ID da distribuiÃ§Ã£o CloudFront nÃ£o foi encontrado no Terraform Output."
            echo "Verifique se a CloudFront Distribution foi criada e se o 'terraform apply' anterior salvou o output no estado remoto."
            exit 1
          fi
              
          # Exporta o ID limpo para ser usado nos passos seguintes (como no job de invalidaÃ§Ã£o)
          echo "CLOUDFRONT_DISTRIBUTION_ID=$ID" >> $GITHUB_ENV
          echo "ðŸŒŽ CloudFront ID exportado com sucesso: $ID"

      - name: ðŸ§¾ Gerar sinalizador de Apply
        id: apply_status
        if: always()
        run: |
          STATUS="no"
          if [ "${{ github.event.inputs.terraform_action }}" == "apply" ] && [ "${{ job.status }}" == "success" ]; then
            STATUS="success"
          fi
          echo "{\"name\": \"setup_aws\", \"apply\": \"${STATUS}\", \"date\": \"$(date '+%Y-%m-%d %H:%M:%S')\"}" > $GITHUB_WORKSPACE/apply_status.txt
          echo "apply_done=${STATUS}" >> $GITHUB_OUTPUT

      - name: ðŸ“¤ Upload do artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-apply-status
          path: ${{ github.workspace }}/apply_status.txt
          retention-days: 1